title: Dark Maps
baseurl: /
permalink: '/:title/'
favicon: favicon.png
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: orange
header:
  logo_img: images/logo.svg
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Features
      url: /features
      style: link
    - label: Pricing
      url: /pricing
      style: link
    - label: FAQ
      url: /faq
      style: link
    - label: Download
      url: download
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/logo-alt.svg
      image_url: /
      image_alt: Footer logo
      content: Encrypted Location Sharing
    - type: footer_nav
      title: Company
      nav_links:
        - label: About Us
          url: /about
          style: link
        # - label: Blog
        #   url: /blog
        #   style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_nav
      title: Community
      nav_links:
        - label: GitHub
          url: 'https://github.com/DarkMaps'
          style: link
          has_icon: true
          icon: github
          icon_position: left
  has_nav: true
  nav_links:
    - label: Terms of Service
      url: /terms-of-service
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
